// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APIDay2.Models;

[Keyless]
[Table("LastTransaction")]
public partial class LastTransaction
{
    public int? userId { get; set; }

    public int? transAmount { get; set; }
}