// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APIDay2.Models;

[Table("SequenceTable")]
public partial class SequenceTable
{
    [Key]
    public int ID { get; set; }

    [StringLength(10)]
    public string name { get; set; }

    [StringLength(50)]
    public string address { get; set; }

    public int? Age { get; set; }
}